# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LoftExperimental < Formula
  desc "Namespace & Virtual Cluster Manager for Kubernetes - Lightweight Virtual Clusters, Self-Service Provisioning for Engineers and 70% Cost Savings with Sleep Mode"
  homepage "https://loft.sh"
  version "3.3.0-beta.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/loft/releases/download/v3.3.0-beta.6/loft-darwin-amd64"
      sha256 "ff63c6d7cc2a192de6a33a1b3d3d156bea9863e8e45ca1ae392994752c9bd2f5"

      def install
        bin.install "loft-darwin-amd64" => "loft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loft-sh/loft/releases/download/v3.3.0-beta.6/loft-darwin-arm64"
      sha256 "456f5345a79ea035dbc0f10bd5c5ea1d2110733b71baa60c709517ef87e0d124"

      def install
        bin.install "loft-darwin-arm64" => "loft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/loft/releases/download/v3.3.0-beta.6/loft-linux-arm"
      sha256 "1b185619409f7ca16a86ce6a0a717e2a1a9d583b7db9c1a750338c8d8246368c"

      def install
        bin.install "loft-linux-arm" => "loft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/loft/releases/download/v3.3.0-beta.6/loft-linux-arm64"
      sha256 "1ba837a6c94088ddae84520e739171aee46856e2fb2cde0cb541466e09823135"

      def install
        bin.install "loft-linux-arm64" => "loft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/loft/releases/download/v3.3.0-beta.6/loft-linux-amd64"
      sha256 "6c1f8234249daf65acd10e3db35abf1d8c19eca068c1e9e4b4de8225988fdfad"

      def install
        bin.install "loft-linux-amd64" => "loft"
      end
    end
  end

  test do
    help_output = "Loft CLI - www.loft.sh"
    assert_match help_output, shell_output("#{bin}/loft --help")
  end
end
