# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LoftExperimental < Formula
  desc "Namespace & Virtual Cluster Manager for Kubernetes - Lightweight Virtual Clusters, Self-Service Provisioning for Engineers and 70% Cost Savings with Sleep Mode"
  homepage "https://loft.sh"
  version "0.0.0-ci.4-do-not-use"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/loft-sh/loft/releases/download/v0.0.0-ci.4-do-not-use/loft-darwin-arm64"
      sha256 "2a0bbf823ada04aa3324f0cf01e376a6f4c4c5d7b1fea7c09660e476638fdf66"

      def install
        bin.install "loft-darwin-arm64" => "loft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/loft/releases/download/v0.0.0-ci.4-do-not-use/loft-darwin-amd64"
      sha256 "b6df7e4159ca3d31a2ac81523c0bf04b68e8c3fe1f1fea1a7a6012afe630683e"

      def install
        bin.install "loft-darwin-amd64" => "loft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/loft/releases/download/v0.0.0-ci.4-do-not-use/loft-linux-arm64"
      sha256 "b7c0213961752de81ca147d54533f1ff5d48504e9ba43a2bc93ee61d518a7310"

      def install
        bin.install "loft-linux-arm64" => "loft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/loft/releases/download/v0.0.0-ci.4-do-not-use/loft-linux-amd64"
      sha256 "f1a1c20960c9bb94ed56fcdb71a92068b13b87b5e993a9cb8605fa798a11925d"

      def install
        bin.install "loft-linux-amd64" => "loft"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/loft/releases/download/v0.0.0-ci.4-do-not-use/loft-linux-arm"
      sha256 "1dd975a14dfde2a908577fb0cb61df261036afeb55dbc15c3857ff28ddcb8e55"

      def install
        bin.install "loft-linux-arm" => "loft"
      end
    end
  end

  test do
    help_output = "Loft CLI - www.loft.sh"
    assert_match help_output, shell_output("#{bin}/loft --help")
  end
end
