# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VclusterExperimental < Formula
  desc "Creates fully functional virtual k8s cluster inside host k8s cluster's namespace"
  homepage "https://www.vcluster.com"
  version "0.19.0-alpha.3"
  license "Apache-2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.0-alpha.3/vcluster-darwin-amd64"
      sha256 "2ac9947be7e35e3a020e662a7233349978d92ee7091ac4017c9c1bb573e6f16f"

      def install
        bin.install "vcluster-darwin-amd64" => "vcluster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.0-alpha.3/vcluster-darwin-arm64"
      sha256 "3f635f6c0337d9539ad14e00ec1206d15178ffef457eb021b869ee72cec6f785"

      def install
        bin.install "vcluster-darwin-arm64" => "vcluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.0-alpha.3/vcluster-linux-arm"
      sha256 "db1e263e2e46cce98f17d77130f2a351eaf597e47549bba14bfd3b436f6cedda"

      def install
        bin.install "vcluster-linux-arm" => "vcluster"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.0-alpha.3/vcluster-linux-amd64"
      sha256 "b5b34f12c4817d3d829073cdd854203e60695e402145817b3c6d8c3a3b905af6"

      def install
        bin.install "vcluster-linux-amd64" => "vcluster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.0-alpha.3/vcluster-linux-arm64"
      sha256 "9ebc24dbfc25fe2a0bb9c145649a06941df7e6eab543e69f9f35c36c931dfcdd"

      def install
        bin.install "vcluster-linux-arm64" => "vcluster"
      end
    end
  end

  conflicts_with "vcluster"
  conflicts_with "loft-sh/tap/vcluster"

  test do
    help_output = "vcluster root command"
    assert_match help_output, shell_output("#{bin}/vcluster --help")
  end
end
