# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  desc "Creates fully functional virtual k8s cluster inside host k8s cluster's namespace"
  homepage "https://www.vcluster.com"
  version "0.19.2"
  license "Apache-2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.2/vcluster-darwin-arm64"
      sha256 "43a1da9b212085934ec6a22589e2375460108a74f4d0b3e2b46e3a10a234c7f9"

      def install
        bin.install "vcluster-darwin-arm64" => "vcluster"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.2/vcluster-darwin-amd64"
      sha256 "6a796f499381f205dc608fa3a315bb6ed52d5f2cac2d1e4043a406bbe6a9b836"

      def install
        bin.install "vcluster-darwin-amd64" => "vcluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.2/vcluster-linux-arm"
      sha256 "54da1d88ddef771196eb990da44d8c25aa8a8a979a8ee623b744cff90e99e3d8"

      def install
        bin.install "vcluster-linux-arm" => "vcluster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.2/vcluster-linux-arm64"
      sha256 "c4879788b17b1113d0e56973b2ca58399a751bc1fb91623cb407dbd13d5a57c9"

      def install
        bin.install "vcluster-linux-arm64" => "vcluster"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.19.2/vcluster-linux-amd64"
      sha256 "ae9098109c1c260da590932dbb5328f99f48295d142fe1270a9798739303f1a7"

      def install
        bin.install "vcluster-linux-amd64" => "vcluster"
      end
    end
  end

  conflicts_with "vcluster"
  conflicts_with "loft-sh/tap/vcluster-experimental"

  test do
    help_output = "vcluster root command"
    assert_match help_output, shell_output("#{bin}/vcluster --help")
  end
end
