# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VclusterExperimental < Formula
  desc "Creates fully functional virtual k8s cluster inside host k8s cluster's namespace"
  homepage "https://www.vcluster.com"
  version "0.35.4-rc.1"
  license "Apache-2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.35.4-rc.1/vcluster-darwin-amd64"
      sha256 "7b0cf3b65030cefec69e731f8221a35d2451e3c3ae494af09b42be2fe7cbe497"

      define_method(:install) do
        bin.install "vcluster-darwin-amd64" => "vcluster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.35.4-rc.1/vcluster-darwin-arm64"
      sha256 "e46b352751c3882ed4ae811467713f222d6ec63c7f97dc908b3ea3bfa6430147"

      define_method(:install) do
        bin.install "vcluster-darwin-arm64" => "vcluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.35.4-rc.1/vcluster-linux-amd64"
      sha256 "a2caf635a1fa44cb71cafceca841e1a97737aeda9683cb8fd07ef08ec0233ccb"
      define_method(:install) do
        bin.install "vcluster-linux-amd64" => "vcluster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loft-sh/vcluster/releases/download/v0.35.4-rc.1/vcluster-linux-arm64"
      sha256 "e9dba510d3b7e9e5d64dce0ed04a4bc730fbe367c1dfc7cdbebebc3cba288453"
      define_method(:install) do
        bin.install "vcluster-linux-arm64" => "vcluster"
      end
    end
  end

  conflicts_with "vcluster"
  conflicts_with "loft-sh/tap/vcluster"

  test do
    help_output = "vcluster root command"
    assert_match help_output, shell_output("#{bin}/vcluster --help")
  end
end
